# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '桃宝' do
pod 'AFNetworking'
pod 'Masonry'


end

target '桃宝Tests' do

end

target '桃宝UITests' do

end

